"""chacha20_fused — generated by ea bind"""
import ctypes as _ct
import numpy as _np
from pathlib import Path as _Path

_lib = _ct.CDLL(str(_Path(__file__).with_name("chacha20_fused.so")))

import os as _os
from concurrent.futures import ThreadPoolExecutor as _TPE
from typing import Optional as _Optional

__all__ = ["chacha20_encrypt_stats", "chacha20_encrypt_stats_parallel"]

_lib.chacha20_encrypt_stats.argtypes = [_ct.POINTER(_ct.c_int32), _ct.POINTER(_ct.c_int32), _ct.c_int32, _ct.POINTER(_ct.c_uint8), _ct.POINTER(_ct.c_uint8), _ct.c_int32, _ct.POINTER(_ct.c_int32), _ct.POINTER(_ct.c_uint8), _ct.POINTER(_ct.c_int32), _ct.POINTER(_ct.c_int32), _ct.POINTER(_ct.c_int64), _ct.POINTER(_ct.c_int32), _ct.POINTER(_ct.c_uint8), _ct.POINTER(_ct.c_uint8)]
_lib.chacha20_encrypt_stats.restype = None

def chacha20_encrypt_stats(key: _np.ndarray, nonce: _np.ndarray, counter: int, plaintext: _np.ndarray, ciphertext: _np.ndarray, ks_i32: _np.ndarray, ks_u8: _np.ndarray, pt_i32: _np.ndarray, ct_i32: _np.ndarray, out_sum: _np.ndarray, out_count: _np.ndarray, out_min: _np.ndarray, out_max: _np.ndarray):
    """chacha20_encrypt_stats(key: ndarray[int32], nonce: ndarray[int32], counter: int, plaintext: ndarray[uint8], ciphertext: ndarray[uint8], ks_i32: ndarray[int32], ks_u8: ndarray[uint8], pt_i32: ndarray[int32], ct_i32: ndarray[int32], out_sum: ndarray[int64], out_count: ndarray[int32], out_min: ndarray[uint8], out_max: ndarray[uint8]) -> None

    C signature: chacha20_encrypt_stats(key: *restrict i32, nonce: *restrict i32, counter: i32, plaintext: *restrict u8, ciphertext: *restrict mut u8, len: i32, ks_i32: *restrict mut i32, ks_u8: *restrict u8, pt_i32: *restrict i32, ct_i32: *restrict mut i32, out_sum: *mut i64, out_count: *mut i32, out_min: *mut u8, out_max: *mut u8) -> void
    """
    if key.dtype != _np.int32:
        raise TypeError("key: expected int32")
    if nonce.dtype != _np.int32:
        raise TypeError("nonce: expected int32")
    if plaintext.dtype != _np.uint8:
        raise TypeError("plaintext: expected uint8")
    if ciphertext.dtype != _np.uint8:
        raise TypeError("ciphertext: expected uint8")
    if ks_i32.dtype != _np.int32:
        raise TypeError("ks_i32: expected int32")
    if ks_u8.dtype != _np.uint8:
        raise TypeError("ks_u8: expected uint8")
    if pt_i32.dtype != _np.int32:
        raise TypeError("pt_i32: expected int32")
    if ct_i32.dtype != _np.int32:
        raise TypeError("ct_i32: expected int32")
    if out_sum.dtype != _np.int64:
        raise TypeError("out_sum: expected int64")
    if out_count.dtype != _np.int32:
        raise TypeError("out_count: expected int32")
    if out_min.dtype != _np.uint8:
        raise TypeError("out_min: expected uint8")
    if out_max.dtype != _np.uint8:
        raise TypeError("out_max: expected uint8")
    _lib.chacha20_encrypt_stats(
        key.ctypes.data_as(_ct.POINTER(_ct.c_int32)),
        nonce.ctypes.data_as(_ct.POINTER(_ct.c_int32)),
        _ct.c_int32(int(counter)),
        plaintext.ctypes.data_as(_ct.POINTER(_ct.c_uint8)),
        ciphertext.ctypes.data_as(_ct.POINTER(_ct.c_uint8)),
        _ct.c_int32(ciphertext.size),
        ks_i32.ctypes.data_as(_ct.POINTER(_ct.c_int32)),
        ks_u8.ctypes.data_as(_ct.POINTER(_ct.c_uint8)),
        pt_i32.ctypes.data_as(_ct.POINTER(_ct.c_int32)),
        ct_i32.ctypes.data_as(_ct.POINTER(_ct.c_int32)),
        out_sum.ctypes.data_as(_ct.POINTER(_ct.c_int64)),
        out_count.ctypes.data_as(_ct.POINTER(_ct.c_int32)),
        out_min.ctypes.data_as(_ct.POINTER(_ct.c_uint8)),
        out_max.ctypes.data_as(_ct.POINTER(_ct.c_uint8))
    )

def chacha20_encrypt_stats_parallel(key: _np.ndarray, nonce: _np.ndarray, counter: int, plaintext: _np.ndarray, ciphertext: _np.ndarray, ks_i32: _np.ndarray, ks_u8: _np.ndarray, pt_i32: _np.ndarray, ct_i32: _np.ndarray, out_sum: _np.ndarray, out_count: _np.ndarray, out_min: _np.ndarray, out_max: _np.ndarray, threads: _Optional[int] = None):
    """Parallel variant of chacha20_encrypt_stats. Splits work across threads using pointer offsets.

    Best for compute-bound kernels (matmul, convolution, FMA-heavy).
    Bandwidth-bound kernels (simple copy, SAXPY, threshold) won't benefit
    and may be slower due to thread pool overhead.
    """
    if key.dtype != _np.int32:
        raise TypeError("key: expected int32")
    if nonce.dtype != _np.int32:
        raise TypeError("nonce: expected int32")
    if plaintext.dtype != _np.uint8:
        raise TypeError("plaintext: expected uint8")
    if ciphertext.dtype != _np.uint8:
        raise TypeError("ciphertext: expected uint8")
    if ks_i32.dtype != _np.int32:
        raise TypeError("ks_i32: expected int32")
    if ks_u8.dtype != _np.uint8:
        raise TypeError("ks_u8: expected uint8")
    if pt_i32.dtype != _np.int32:
        raise TypeError("pt_i32: expected int32")
    if ct_i32.dtype != _np.int32:
        raise TypeError("ct_i32: expected int32")
    if out_sum.dtype != _np.int64:
        raise TypeError("out_sum: expected int64")
    if out_count.dtype != _np.int32:
        raise TypeError("out_count: expected int32")
    if out_min.dtype != _np.uint8:
        raise TypeError("out_min: expected uint8")
    if out_max.dtype != _np.uint8:
        raise TypeError("out_max: expected uint8")
    _n = ciphertext.size
    _threads = threads or _os.cpu_count() or 1
    if _threads == 1 or _n < _threads:
        chacha20_encrypt_stats(key, nonce, counter, plaintext, ciphertext, ks_i32, ks_u8, pt_i32, ct_i32, out_sum, out_count, out_min, out_max)
        return
    _elem = _ct.sizeof(_ct.c_int32)
    _chunk = _n // _threads
    def _worker(_start, _count):
        _lib.chacha20_encrypt_stats(
            _ct.cast(_ct.c_void_p(key.ctypes.data + _start * _elem), _ct.POINTER(_ct.c_int32)),
            _ct.cast(_ct.c_void_p(nonce.ctypes.data + _start * _elem), _ct.POINTER(_ct.c_int32)),
            _ct.c_int32(int(counter)),
            _ct.cast(_ct.c_void_p(plaintext.ctypes.data + _start * _elem), _ct.POINTER(_ct.c_uint8)),
            _ct.cast(_ct.c_void_p(ciphertext.ctypes.data + _start * _elem), _ct.POINTER(_ct.c_uint8)),
            _ct.c_int32(_count),
            _ct.cast(_ct.c_void_p(ks_i32.ctypes.data + _start * _elem), _ct.POINTER(_ct.c_int32)),
            _ct.cast(_ct.c_void_p(ks_u8.ctypes.data + _start * _elem), _ct.POINTER(_ct.c_uint8)),
            _ct.cast(_ct.c_void_p(pt_i32.ctypes.data + _start * _elem), _ct.POINTER(_ct.c_int32)),
            _ct.cast(_ct.c_void_p(ct_i32.ctypes.data + _start * _elem), _ct.POINTER(_ct.c_int32)),
            _ct.cast(_ct.c_void_p(out_sum.ctypes.data + _start * _elem), _ct.POINTER(_ct.c_int64)),
            _ct.cast(_ct.c_void_p(out_count.ctypes.data + _start * _elem), _ct.POINTER(_ct.c_int32)),
            _ct.cast(_ct.c_void_p(out_min.ctypes.data + _start * _elem), _ct.POINTER(_ct.c_uint8)),
            _ct.cast(_ct.c_void_p(out_max.ctypes.data + _start * _elem), _ct.POINTER(_ct.c_uint8))
        )
    with _TPE(max_workers=_threads) as _pool:
        _futures = []
        for _t in range(_threads):
            _s = _t * _chunk
            _c = _n - _s if _t == _threads - 1 else _chunk
            _futures.append(_pool.submit(_worker, _s, _c))
        for _f in _futures:
            _f.result()

